code --install-extension abusaidm.html-snippets
code --install-extension AESSoft.aessoft-class-autocomplete
code --install-extension alexiv.vscode-angular2-files
code --install-extension Angular.ng-template
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.ts-tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension infinity1207.angular2-switcher
code --install-extension jakethashi.vscode-angular2-emmet
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension liviuschera.noctis
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension PKief.material-icon-theme